### ISSUE TITLE
heroku deployment 

### ISSUE THREAD

**Issue by ghost** [akump/MS-Teams-Always-Available#3]
can this be deployed to heroku, so we don't need to have the pc on all the time?

**Comment by akump** [comment]
Hey @co5mo ,

Yes this could be technically deployed on heroku. This specific repo is for this logic to run as a chrome extension. This makes the extension more accessible as users won't have to do anything specific for them. The main issue with deploying to heroku is getting the auth token for Microsoft. The logic in `src/js/script.js` grabs this from the user's local storage and then makes the force availability call. I'm not sure how often this token expires. You'd have to get this token for each call in your heroku deployment and I'm not sure that's possible. If you have any suggestions, I can investigate how to get the auth token.
