### ISSUE TITLE
teams.microsoft.com.mcas.ms

### ISSUE THREAD

**Issue by StraggleCraft** [akump/MS-Teams-Always-Available#6]
Hello can you please add the following hostname to the plugin?
teams.microsoft.com.mcas.ms

mcas.ms is used by Microsoft's cloud security along with other hostnames...  More info here:  https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy-url

**Comment by akump** [comment]
Hey this is a duplicate of https://github.com/akump/MS-Teams-Always-Available/issues/4. I made a comment on a potential fix. Please test it out.

**Comment by akump** [comment]
Closing this for same reason as #4
