### ISSUE TITLE
[Feature Request] Status Awareness - aka preserve the status of the logged in user if they're in a call/meeting/presenting

### ISSUE THREAD

**Issue by NitroV** [akump/MS-Teams-Always-Available#9]
**Describe the bug**

As of now, if the logged in user is in a call/meeting or presenting, the extension will continue to overwrite that [status](https://docs.microsoft.com/en-us/microsoftteams/presence-admins) with "available" or whichever one is selected from the extension in predefined intervals.

Would it be technically possible to gather the current status of the user, if it's set to "in a call", "in a meeting" & "presenting", simply ping the presence servers with same status or go into idle state until it goes back to one of the user-selectable [statuses](https://support.microsoft.com/en-us/office/change-your-status-in-teams-ce36ed14-6bc9-4775-a33e-6629ba4ff78e), and then only continue pinging with previously selected status from within the extension to remain available?

**Steps to reproduce**

Prereq: Have 2-3 teams accounts (own or friends), have the extension installed on your end. Multiple computers/browsers/instances

1. Call other user and observe the status changing from in a call to available
2. Do screen share and observe the status changing from presenting to available
3. Add third person to the call and observe the status changing from in a meeting to available

Please provide your team's URL: Standard URL ([teams.microsoft.com](https://teams.microsoft.com))

Also I've realized the latest revision of the extension have introduced a subscription model, it would be nicer if it was a one time payment but hey, I understand nobody is entitled to have everything for free but please consider having a free tier with [bare minimum functionality](https://i.imgur.com/SjZXGBJ.png) (like only with "available" status, no counts shown, cant disable from gui, no duration selection etc.) instead of trial and leave fancy options as a part of paid tier. 

Moreover it would be nicer to have a countdown till the next refresh instead of just a count imo.

Please consider if any of this is technically feasible to implement and do let me know. Thanks in advance for developing this wonderful extension!

**Comment by akump** [comment]
@NitroV 

Hey NitroV,
I agree with your feature request. If you're legitimately in a meeting, you wouldn't want to the extension to display a green available, but to be seen as red/in a meeting. I've looked through Microsoft's documentation, and I haven't been able to find much unfortunately. Even if I was able to code up this feature, I think it'd best for this to be a toggle/setting as maybe everyone doesn't want this by default. 

I gave the free tier/advanced features behind a paywall some thought. I ultimately decided against it as the main additional features are additional status types and the time window to run the extension. I'm currently testing the subscription model, but if it ultimately fails, I will reassess to the free/pro model.

Really appreciate your feedback and support. If I find more about determining if a user is in a meeting, I will let you know and implement it when I can. 

Andrew

**Comment by NitroV** [comment]
Hi Andrew,

Thanks for the detailed reply. As you've pointed out, giving end user the choice is always a good thing and I'd be more than happy to have it as a toggle switch that can be turned on/off based on users' needs if the feature ever gets implemented.

If it helps, to achieve the functionality previously mentioned, I used to have an old smartphone running Teams app with screen timeout disabled during work hours to maintain the availability and it perfectly adapts to the dynamic statuses (in a call/meeting etc.) on computer without any issues.

So in theory, if the extension could maintain the availability the same way app does, everything would would work as intended however the fact that the inner workings of these programs are not well documented and are proprietary does not help in this regard.

As much as I'd like to stick to what works, this _always-on second device_ approach requires its battery to be swapped out every 6-8 months and that is definitely not kind to the environment.

Either way, I'll keep an eye out for new developments of the extension and I truly do hope the subscription model works out for you. Looking forward to whats to come in the future!

Thanks and regards,
NitroV 

Update: Came across these docs [Get presence](https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0) / [Set presence](https://docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-1.0) and [this blog post](https://www.damobird365.com/teams-status-update-via-power-automate/)
